# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ubuntu/miniconda3/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ubuntu/miniconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/SCServo_Linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/SCServo_Linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/ubuntu/miniconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ubuntu/miniconda3/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/SCServo_Linux/CMakeFiles /home/ubuntu/SCServo_Linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/SCServo_Linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SCServo

# Build rule for target.
SCServo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SCServo
.PHONY : SCServo

# fast build rule for target.
SCServo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/build
.PHONY : SCServo/fast

#=============================================================================
# Target rules for targets named scservo_python

# Build rule for target.
scservo_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scservo_python
.PHONY : scservo_python

# fast build rule for target.
scservo_python/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scservo_python.dir/build.make CMakeFiles/scservo_python.dir/build
.PHONY : scservo_python/fast

#=============================================================================
# Target rules for targets named nanobind-static

# Build rule for target.
nanobind-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanobind-static
.PHONY : nanobind-static

# fast build rule for target.
nanobind-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/build
.PHONY : nanobind-static/fast

SCS.o: SCS.cpp.o
.PHONY : SCS.o

# target to build an object file
SCS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.o
.PHONY : SCS.cpp.o

SCS.i: SCS.cpp.i
.PHONY : SCS.i

# target to preprocess a source file
SCS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.i
.PHONY : SCS.cpp.i

SCS.s: SCS.cpp.s
.PHONY : SCS.s

# target to generate assembly for a file
SCS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.s
.PHONY : SCS.cpp.s

SCSCL.o: SCSCL.cpp.o
.PHONY : SCSCL.o

# target to build an object file
SCSCL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.o
.PHONY : SCSCL.cpp.o

SCSCL.i: SCSCL.cpp.i
.PHONY : SCSCL.i

# target to preprocess a source file
SCSCL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.i
.PHONY : SCSCL.cpp.i

SCSCL.s: SCSCL.cpp.s
.PHONY : SCSCL.s

# target to generate assembly for a file
SCSCL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.s
.PHONY : SCSCL.cpp.s

SCSerial.o: SCSerial.cpp.o
.PHONY : SCSerial.o

# target to build an object file
SCSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.o
.PHONY : SCSerial.cpp.o

SCSerial.i: SCSerial.cpp.i
.PHONY : SCSerial.i

# target to preprocess a source file
SCSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.i
.PHONY : SCSerial.cpp.i

SCSerial.s: SCSerial.cpp.s
.PHONY : SCSerial.s

# target to generate assembly for a file
SCSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.s
.PHONY : SCSerial.cpp.s

SMSCL.o: SMSCL.cpp.o
.PHONY : SMSCL.o

# target to build an object file
SMSCL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.o
.PHONY : SMSCL.cpp.o

SMSCL.i: SMSCL.cpp.i
.PHONY : SMSCL.i

# target to preprocess a source file
SMSCL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.i
.PHONY : SMSCL.cpp.i

SMSCL.s: SMSCL.cpp.s
.PHONY : SMSCL.s

# target to generate assembly for a file
SMSCL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.s
.PHONY : SMSCL.cpp.s

SMS_STS.o: SMS_STS.cpp.o
.PHONY : SMS_STS.o

# target to build an object file
SMS_STS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.o
.PHONY : SMS_STS.cpp.o

SMS_STS.i: SMS_STS.cpp.i
.PHONY : SMS_STS.i

# target to preprocess a source file
SMS_STS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.i
.PHONY : SMS_STS.cpp.i

SMS_STS.s: SMS_STS.cpp.s
.PHONY : SMS_STS.s

# target to generate assembly for a file
SMS_STS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.s
.PHONY : SMS_STS.cpp.s

extern/nanobind/src/common.o: extern/nanobind/src/common.cpp.o
.PHONY : extern/nanobind/src/common.o

# target to build an object file
extern/nanobind/src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/common.cpp.o
.PHONY : extern/nanobind/src/common.cpp.o

extern/nanobind/src/common.i: extern/nanobind/src/common.cpp.i
.PHONY : extern/nanobind/src/common.i

# target to preprocess a source file
extern/nanobind/src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/common.cpp.i
.PHONY : extern/nanobind/src/common.cpp.i

extern/nanobind/src/common.s: extern/nanobind/src/common.cpp.s
.PHONY : extern/nanobind/src/common.s

# target to generate assembly for a file
extern/nanobind/src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/common.cpp.s
.PHONY : extern/nanobind/src/common.cpp.s

extern/nanobind/src/error.o: extern/nanobind/src/error.cpp.o
.PHONY : extern/nanobind/src/error.o

# target to build an object file
extern/nanobind/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/error.cpp.o
.PHONY : extern/nanobind/src/error.cpp.o

extern/nanobind/src/error.i: extern/nanobind/src/error.cpp.i
.PHONY : extern/nanobind/src/error.i

# target to preprocess a source file
extern/nanobind/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/error.cpp.i
.PHONY : extern/nanobind/src/error.cpp.i

extern/nanobind/src/error.s: extern/nanobind/src/error.cpp.s
.PHONY : extern/nanobind/src/error.s

# target to generate assembly for a file
extern/nanobind/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/error.cpp.s
.PHONY : extern/nanobind/src/error.cpp.s

extern/nanobind/src/implicit.o: extern/nanobind/src/implicit.cpp.o
.PHONY : extern/nanobind/src/implicit.o

# target to build an object file
extern/nanobind/src/implicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/implicit.cpp.o
.PHONY : extern/nanobind/src/implicit.cpp.o

extern/nanobind/src/implicit.i: extern/nanobind/src/implicit.cpp.i
.PHONY : extern/nanobind/src/implicit.i

# target to preprocess a source file
extern/nanobind/src/implicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/implicit.cpp.i
.PHONY : extern/nanobind/src/implicit.cpp.i

extern/nanobind/src/implicit.s: extern/nanobind/src/implicit.cpp.s
.PHONY : extern/nanobind/src/implicit.s

# target to generate assembly for a file
extern/nanobind/src/implicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/implicit.cpp.s
.PHONY : extern/nanobind/src/implicit.cpp.s

extern/nanobind/src/nb_enum.o: extern/nanobind/src/nb_enum.cpp.o
.PHONY : extern/nanobind/src/nb_enum.o

# target to build an object file
extern/nanobind/src/nb_enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_enum.cpp.o
.PHONY : extern/nanobind/src/nb_enum.cpp.o

extern/nanobind/src/nb_enum.i: extern/nanobind/src/nb_enum.cpp.i
.PHONY : extern/nanobind/src/nb_enum.i

# target to preprocess a source file
extern/nanobind/src/nb_enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_enum.cpp.i
.PHONY : extern/nanobind/src/nb_enum.cpp.i

extern/nanobind/src/nb_enum.s: extern/nanobind/src/nb_enum.cpp.s
.PHONY : extern/nanobind/src/nb_enum.s

# target to generate assembly for a file
extern/nanobind/src/nb_enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_enum.cpp.s
.PHONY : extern/nanobind/src/nb_enum.cpp.s

extern/nanobind/src/nb_ft.o: extern/nanobind/src/nb_ft.cpp.o
.PHONY : extern/nanobind/src/nb_ft.o

# target to build an object file
extern/nanobind/src/nb_ft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ft.cpp.o
.PHONY : extern/nanobind/src/nb_ft.cpp.o

extern/nanobind/src/nb_ft.i: extern/nanobind/src/nb_ft.cpp.i
.PHONY : extern/nanobind/src/nb_ft.i

# target to preprocess a source file
extern/nanobind/src/nb_ft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ft.cpp.i
.PHONY : extern/nanobind/src/nb_ft.cpp.i

extern/nanobind/src/nb_ft.s: extern/nanobind/src/nb_ft.cpp.s
.PHONY : extern/nanobind/src/nb_ft.s

# target to generate assembly for a file
extern/nanobind/src/nb_ft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ft.cpp.s
.PHONY : extern/nanobind/src/nb_ft.cpp.s

extern/nanobind/src/nb_func.o: extern/nanobind/src/nb_func.cpp.o
.PHONY : extern/nanobind/src/nb_func.o

# target to build an object file
extern/nanobind/src/nb_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_func.cpp.o
.PHONY : extern/nanobind/src/nb_func.cpp.o

extern/nanobind/src/nb_func.i: extern/nanobind/src/nb_func.cpp.i
.PHONY : extern/nanobind/src/nb_func.i

# target to preprocess a source file
extern/nanobind/src/nb_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_func.cpp.i
.PHONY : extern/nanobind/src/nb_func.cpp.i

extern/nanobind/src/nb_func.s: extern/nanobind/src/nb_func.cpp.s
.PHONY : extern/nanobind/src/nb_func.s

# target to generate assembly for a file
extern/nanobind/src/nb_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_func.cpp.s
.PHONY : extern/nanobind/src/nb_func.cpp.s

extern/nanobind/src/nb_internals.o: extern/nanobind/src/nb_internals.cpp.o
.PHONY : extern/nanobind/src/nb_internals.o

# target to build an object file
extern/nanobind/src/nb_internals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_internals.cpp.o
.PHONY : extern/nanobind/src/nb_internals.cpp.o

extern/nanobind/src/nb_internals.i: extern/nanobind/src/nb_internals.cpp.i
.PHONY : extern/nanobind/src/nb_internals.i

# target to preprocess a source file
extern/nanobind/src/nb_internals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_internals.cpp.i
.PHONY : extern/nanobind/src/nb_internals.cpp.i

extern/nanobind/src/nb_internals.s: extern/nanobind/src/nb_internals.cpp.s
.PHONY : extern/nanobind/src/nb_internals.s

# target to generate assembly for a file
extern/nanobind/src/nb_internals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_internals.cpp.s
.PHONY : extern/nanobind/src/nb_internals.cpp.s

extern/nanobind/src/nb_ndarray.o: extern/nanobind/src/nb_ndarray.cpp.o
.PHONY : extern/nanobind/src/nb_ndarray.o

# target to build an object file
extern/nanobind/src/nb_ndarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ndarray.cpp.o
.PHONY : extern/nanobind/src/nb_ndarray.cpp.o

extern/nanobind/src/nb_ndarray.i: extern/nanobind/src/nb_ndarray.cpp.i
.PHONY : extern/nanobind/src/nb_ndarray.i

# target to preprocess a source file
extern/nanobind/src/nb_ndarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ndarray.cpp.i
.PHONY : extern/nanobind/src/nb_ndarray.cpp.i

extern/nanobind/src/nb_ndarray.s: extern/nanobind/src/nb_ndarray.cpp.s
.PHONY : extern/nanobind/src/nb_ndarray.s

# target to generate assembly for a file
extern/nanobind/src/nb_ndarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_ndarray.cpp.s
.PHONY : extern/nanobind/src/nb_ndarray.cpp.s

extern/nanobind/src/nb_static_property.o: extern/nanobind/src/nb_static_property.cpp.o
.PHONY : extern/nanobind/src/nb_static_property.o

# target to build an object file
extern/nanobind/src/nb_static_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_static_property.cpp.o
.PHONY : extern/nanobind/src/nb_static_property.cpp.o

extern/nanobind/src/nb_static_property.i: extern/nanobind/src/nb_static_property.cpp.i
.PHONY : extern/nanobind/src/nb_static_property.i

# target to preprocess a source file
extern/nanobind/src/nb_static_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_static_property.cpp.i
.PHONY : extern/nanobind/src/nb_static_property.cpp.i

extern/nanobind/src/nb_static_property.s: extern/nanobind/src/nb_static_property.cpp.s
.PHONY : extern/nanobind/src/nb_static_property.s

# target to generate assembly for a file
extern/nanobind/src/nb_static_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_static_property.cpp.s
.PHONY : extern/nanobind/src/nb_static_property.cpp.s

extern/nanobind/src/nb_type.o: extern/nanobind/src/nb_type.cpp.o
.PHONY : extern/nanobind/src/nb_type.o

# target to build an object file
extern/nanobind/src/nb_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_type.cpp.o
.PHONY : extern/nanobind/src/nb_type.cpp.o

extern/nanobind/src/nb_type.i: extern/nanobind/src/nb_type.cpp.i
.PHONY : extern/nanobind/src/nb_type.i

# target to preprocess a source file
extern/nanobind/src/nb_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_type.cpp.i
.PHONY : extern/nanobind/src/nb_type.cpp.i

extern/nanobind/src/nb_type.s: extern/nanobind/src/nb_type.cpp.s
.PHONY : extern/nanobind/src/nb_type.s

# target to generate assembly for a file
extern/nanobind/src/nb_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/nb_type.cpp.s
.PHONY : extern/nanobind/src/nb_type.cpp.s

extern/nanobind/src/trampoline.o: extern/nanobind/src/trampoline.cpp.o
.PHONY : extern/nanobind/src/trampoline.o

# target to build an object file
extern/nanobind/src/trampoline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/trampoline.cpp.o
.PHONY : extern/nanobind/src/trampoline.cpp.o

extern/nanobind/src/trampoline.i: extern/nanobind/src/trampoline.cpp.i
.PHONY : extern/nanobind/src/trampoline.i

# target to preprocess a source file
extern/nanobind/src/trampoline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/trampoline.cpp.i
.PHONY : extern/nanobind/src/trampoline.cpp.i

extern/nanobind/src/trampoline.s: extern/nanobind/src/trampoline.cpp.s
.PHONY : extern/nanobind/src/trampoline.s

# target to generate assembly for a file
extern/nanobind/src/trampoline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/extern/nanobind/src/trampoline.cpp.s
.PHONY : extern/nanobind/src/trampoline.cpp.s

src/bindings.o: src/bindings.cpp.o
.PHONY : src/bindings.o

# target to build an object file
src/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scservo_python.dir/build.make CMakeFiles/scservo_python.dir/src/bindings.cpp.o
.PHONY : src/bindings.cpp.o

src/bindings.i: src/bindings.cpp.i
.PHONY : src/bindings.i

# target to preprocess a source file
src/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scservo_python.dir/build.make CMakeFiles/scservo_python.dir/src/bindings.cpp.i
.PHONY : src/bindings.cpp.i

src/bindings.s: src/bindings.cpp.s
.PHONY : src/bindings.s

# target to generate assembly for a file
src/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scservo_python.dir/build.make CMakeFiles/scservo_python.dir/src/bindings.cpp.s
.PHONY : src/bindings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SCServo"
	@echo "... nanobind-static"
	@echo "... scservo_python"
	@echo "... SCS.o"
	@echo "... SCS.i"
	@echo "... SCS.s"
	@echo "... SCSCL.o"
	@echo "... SCSCL.i"
	@echo "... SCSCL.s"
	@echo "... SCSerial.o"
	@echo "... SCSerial.i"
	@echo "... SCSerial.s"
	@echo "... SMSCL.o"
	@echo "... SMSCL.i"
	@echo "... SMSCL.s"
	@echo "... SMS_STS.o"
	@echo "... SMS_STS.i"
	@echo "... SMS_STS.s"
	@echo "... extern/nanobind/src/common.o"
	@echo "... extern/nanobind/src/common.i"
	@echo "... extern/nanobind/src/common.s"
	@echo "... extern/nanobind/src/error.o"
	@echo "... extern/nanobind/src/error.i"
	@echo "... extern/nanobind/src/error.s"
	@echo "... extern/nanobind/src/implicit.o"
	@echo "... extern/nanobind/src/implicit.i"
	@echo "... extern/nanobind/src/implicit.s"
	@echo "... extern/nanobind/src/nb_enum.o"
	@echo "... extern/nanobind/src/nb_enum.i"
	@echo "... extern/nanobind/src/nb_enum.s"
	@echo "... extern/nanobind/src/nb_ft.o"
	@echo "... extern/nanobind/src/nb_ft.i"
	@echo "... extern/nanobind/src/nb_ft.s"
	@echo "... extern/nanobind/src/nb_func.o"
	@echo "... extern/nanobind/src/nb_func.i"
	@echo "... extern/nanobind/src/nb_func.s"
	@echo "... extern/nanobind/src/nb_internals.o"
	@echo "... extern/nanobind/src/nb_internals.i"
	@echo "... extern/nanobind/src/nb_internals.s"
	@echo "... extern/nanobind/src/nb_ndarray.o"
	@echo "... extern/nanobind/src/nb_ndarray.i"
	@echo "... extern/nanobind/src/nb_ndarray.s"
	@echo "... extern/nanobind/src/nb_static_property.o"
	@echo "... extern/nanobind/src/nb_static_property.i"
	@echo "... extern/nanobind/src/nb_static_property.s"
	@echo "... extern/nanobind/src/nb_type.o"
	@echo "... extern/nanobind/src/nb_type.i"
	@echo "... extern/nanobind/src/nb_type.s"
	@echo "... extern/nanobind/src/trampoline.o"
	@echo "... extern/nanobind/src/trampoline.i"
	@echo "... extern/nanobind/src/trampoline.s"
	@echo "... src/bindings.o"
	@echo "... src/bindings.i"
	@echo "... src/bindings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

