# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/ros2_ws/src/pan_tilt_ros/include/SCServo_Linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/ros2_ws/src/pan_tilt_ros/include/SCServo_Linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ros2_ws/src/pan_tilt_ros/include/SCServo_Linux/CMakeFiles /home/ubuntu/ros2_ws/src/pan_tilt_ros/include/SCServo_Linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ros2_ws/src/pan_tilt_ros/include/SCServo_Linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SCServo

# Build rule for target.
SCServo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SCServo
.PHONY : SCServo

# fast build rule for target.
SCServo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/build
.PHONY : SCServo/fast

SCS.o: SCS.cpp.o
.PHONY : SCS.o

# target to build an object file
SCS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.o
.PHONY : SCS.cpp.o

SCS.i: SCS.cpp.i
.PHONY : SCS.i

# target to preprocess a source file
SCS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.i
.PHONY : SCS.cpp.i

SCS.s: SCS.cpp.s
.PHONY : SCS.s

# target to generate assembly for a file
SCS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCS.cpp.s
.PHONY : SCS.cpp.s

SCSCL.o: SCSCL.cpp.o
.PHONY : SCSCL.o

# target to build an object file
SCSCL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.o
.PHONY : SCSCL.cpp.o

SCSCL.i: SCSCL.cpp.i
.PHONY : SCSCL.i

# target to preprocess a source file
SCSCL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.i
.PHONY : SCSCL.cpp.i

SCSCL.s: SCSCL.cpp.s
.PHONY : SCSCL.s

# target to generate assembly for a file
SCSCL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSCL.cpp.s
.PHONY : SCSCL.cpp.s

SCSerial.o: SCSerial.cpp.o
.PHONY : SCSerial.o

# target to build an object file
SCSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.o
.PHONY : SCSerial.cpp.o

SCSerial.i: SCSerial.cpp.i
.PHONY : SCSerial.i

# target to preprocess a source file
SCSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.i
.PHONY : SCSerial.cpp.i

SCSerial.s: SCSerial.cpp.s
.PHONY : SCSerial.s

# target to generate assembly for a file
SCSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SCSerial.cpp.s
.PHONY : SCSerial.cpp.s

SMSBL.o: SMSBL.cpp.o
.PHONY : SMSBL.o

# target to build an object file
SMSBL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSBL.cpp.o
.PHONY : SMSBL.cpp.o

SMSBL.i: SMSBL.cpp.i
.PHONY : SMSBL.i

# target to preprocess a source file
SMSBL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSBL.cpp.i
.PHONY : SMSBL.cpp.i

SMSBL.s: SMSBL.cpp.s
.PHONY : SMSBL.s

# target to generate assembly for a file
SMSBL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSBL.cpp.s
.PHONY : SMSBL.cpp.s

SMSCL.o: SMSCL.cpp.o
.PHONY : SMSCL.o

# target to build an object file
SMSCL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.o
.PHONY : SMSCL.cpp.o

SMSCL.i: SMSCL.cpp.i
.PHONY : SMSCL.i

# target to preprocess a source file
SMSCL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.i
.PHONY : SMSCL.cpp.i

SMSCL.s: SMSCL.cpp.s
.PHONY : SMSCL.s

# target to generate assembly for a file
SMSCL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMSCL.cpp.s
.PHONY : SMSCL.cpp.s

SMS_STS.o: SMS_STS.cpp.o
.PHONY : SMS_STS.o

# target to build an object file
SMS_STS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.o
.PHONY : SMS_STS.cpp.o

SMS_STS.i: SMS_STS.cpp.i
.PHONY : SMS_STS.i

# target to preprocess a source file
SMS_STS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.i
.PHONY : SMS_STS.cpp.i

SMS_STS.s: SMS_STS.cpp.s
.PHONY : SMS_STS.s

# target to generate assembly for a file
SMS_STS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SCServo.dir/build.make CMakeFiles/SCServo.dir/SMS_STS.cpp.s
.PHONY : SMS_STS.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SCServo"
	@echo "... SCS.o"
	@echo "... SCS.i"
	@echo "... SCS.s"
	@echo "... SCSCL.o"
	@echo "... SCSCL.i"
	@echo "... SCSCL.s"
	@echo "... SCSerial.o"
	@echo "... SCSerial.i"
	@echo "... SCSerial.s"
	@echo "... SMSBL.o"
	@echo "... SMSBL.i"
	@echo "... SMSBL.s"
	@echo "... SMSCL.o"
	@echo "... SMSCL.i"
	@echo "... SMSCL.s"
	@echo "... SMS_STS.o"
	@echo "... SMS_STS.i"
	@echo "... SMS_STS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

